### ISSUE TITLE
Uncaught ModuleNotFoundError: No module named 'PIL'


### ISSUE THREAD

**Issue by baditaflorin** [maptiler/qgis-maptiler-plugin#135] opened 2020-09-26 00:11 UTC
Couldn't load plugin 'qgis-maptiler-plugin' due to an error when calling its classFactory() method
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "/Applications/QGIS3.4.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/florin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/__init__.py", line 35, in classFactory
    from .maptiler import MapTiler
  File "/Applications/QGIS3.4.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/florin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/maptiler.py", line 34, in <module>
    from .browser_root_collection import DataItemProvider
  File "/Applications/QGIS3.4.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/florin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/browser_root_collection.py", line 7, in <module>
    from .browser_mapitem import MapDataItem
  File "/Applications/QGIS3.4.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/florin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/browser_mapitem.py", line 11, in <module>
    from .gl2qgis import converter
  File "/Applications/QGIS3.4.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/florin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/gl2qgis/converter.py", line 19, in <module>
    from PIL import Image
  File "/Applications/QGIS3.4.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'PIL'

```
qgis-maptiler-plugin 1.1.3, QGIS 3.4.5-Madeira on Darwin 19.6.0

**Comment by tabell** [comment] 2020-10-01 18:39
I am experiencing the same error on QGIS 3.14.16-1 on arch linux

**Comment by lazaa32** [comment] 2020-10-02 07:34
Possible duplicate of #125. Is Pillow installed on your machine? If not:
`python3 -m pip install Pillow==7.2.0`

**Comment by tabell** [comment] 2020-10-04 23:12
@lazaa32 this resolved the issue for me, thanks!

**Closed** 2020-10-06 08:24 UTC

**Comment by SGREEN1994** [comment] 2022-09-09 15:56
Hi all, 
I keep recieving the same error: Couldn't load plugin 'HotSpotAnalysis_Plugin-qgis3pysal2' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'PIL' 

I've installed pillow, tried upgrading, tried uninstalling and reinstalling and I still receive the same error. It is like GIS is not finding the plugin. 
I am using:

QGIS version | 3.22.10-Białowieża | QGIS code revision | 44701d6dd7
-- | -- | -- | --
Qt version | 5.14.2
Python version | 3.8.7
GDAL/OGR version | 3.2.1
PROJ version | 6.3.2
EPSG Registry database version | v9.8.6 (2020-01-22)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.31.1
PostgreSQL client version | 12.3
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.4
OS version | macOS 12.4

Active Python plugins
--
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.5

The error looks like this: 
Couldn't load plugin 'HotSpotAnalysis_Plugin-qgis3pysal2' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'PIL' 
Traceback (most recent call last):
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/martinarvaez/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/HotSpotAnalysis_Plugin-qgis3pysal2/__init__.py", line 34, in classFactory
    from .hotspot_analysis import HotspotAnalysis
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/martinarvaez/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/HotSpotAnalysis_Plugin-qgis3pysal2/hotspot_analysis.py", line 38, in 
    import pysal
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/pysal/__init__.py", line 3, in 
    from . import explore
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/pysal/explore/__init__.py", line 4, in 
    import pointpats
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/pointpats/__init__.py", line 4, in 
    from .pointpattern import PointPattern
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/pointpats/pointpattern.py", line 12, in 
    from matplotlib import pyplot as plt
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg/matplotlib/pyplot.py", line 36, in 
    import matplotlib.colorbar
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg/matplotlib/colorbar.py", line 44, in 
    import matplotlib.contour as contour
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg/matplotlib/contour.py", line 17, in 
    import matplotlib.text as text
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg/matplotlib/text.py", line 16, in 
    from .textpath import TextPath  # Unused, but imported by others.
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg/matplotlib/textpath.py", line 11, in 
    from matplotlib.mathtext import MathTextParser
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg/matplotlib/mathtext.py", line 27, in 
    from PIL import Image
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'PIL'


Python version: 3.8.7 (default, Feb 10 2021, 09:04:08) [Clang 12.0.0 (clang-1200.0.32.29)] 
QGIS version: 3.22.10-Białowieża Białowieża, 44701d6dd7 

Python Path:
/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python
/Users/martinarvaez/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/martinarvaez/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/opencv_contrib_python-4.3.0.36-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/affine-2.3.0-py3.8.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/numba-0.50.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Rtree-0.9.4-py3.8.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/click_plugins-1.1.1-py3.8.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/patsy-0.5.1-py3.8.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python38.zip
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/pyproj-2.6.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/snuggs-1.4.7-py3.8.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/GDAL-3.2.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/pandas-1.1.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/scipy-1.5.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/lib-dynload
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/statsmodels-0.11.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/rasterio-1.1.5-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/geopandas-0.8.1-py3.8.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/netCDF4-1.5.4-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/cftime-1.2.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/numpy-1.20.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Fiona-1.8.13.post1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages
/Users/martinarvaez/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Volumes/DISK_IMG/GIS-SpatialAnalysis-WSDecadeTracking

Any clue what else I can try?

**Comment by lazaa32** [comment] 2022-09-09 18:12
Hi @SGREEN1994 
It seems to me, that your error is not related to MapTiler plugin at all. 
You might have a better chance in the plugin repository: https://github.com/danioxoli/HotSpotAnalysis_Plugin
