### ISSUE TITLE
Move the Mapbox to QGIS styling to QGIS processing tools

### ISSUE THREAD

**Issue by saberraz** [maptiler/qgis-maptiler-plugin#106] opened 2020-06-22 16:25 UTC
Related to: https://github.com/qgis/QGIS/issues/37152

**Comment by wonder-sk** [comment] 2020-09-05 09:59
See also the QGIS pull request from Nyall that ports the style conversion to QGIS core: https://github.com/qgis/QGIS/pull/38599

**Comment by lazaa32** [comment] 2021-09-17 09:13
Duplicate of #133

**Closed by lazaa32** 2021-09-17 09:13 UTC
